name: ChatFilter
version: 1.1.0
main: me.itsmyunderscore.ChatFilter
api-version: 1.17
authors: [ ItsMYunderscore ]
description: Chat Filter by ItsMYunderscore
website: https://itsmyunderscore.me/
commands:
  ChatFilter:
    description: You will never know
  filter:
    description: Main control command
  cfdebug:
    description: Debug is switched by this
  cflang:
    description: In game message editor