name: ItsMY_ChatFilter
version: @version@
main: me.itsmyunderscore.ChatFilter
api-version: 1.17
authors: [ ItsMYunderscore ]
description: Basic ChatFilter
website: https://itsmyunderscore.me/
commands:
  cfdebug:
    name: Debug is switched by this

  filter:
    name: Not implemented yet
